export interface dummyHistoryItem {
  name?: string;
  car?: string;
  date?: string;
  time?: string;
  category?: string;
}

export const dummyhistory = [
  {
    name: "Nate",
    car: "Mustang",
    date: "2025-10-17",
    time: "09:00",
    category: "upcoming",
  },
  {
    name: "William",
    car: "Civic",
    date: "2025-10-16",
    time: "14:30",
    category: "completed",
  },
  {
    name: "Adebato",
    car: "Corolla",
    date: "2025-10-15",
    time: "11:15",
    category: "completed",
  },
  {
    name: "Chloe",
    car: "Accord",
    date: "2025-10-14",
    time: "16:45",
    category: "cancelled",
  },
  {
    name: "Liam",
    car: "Camry",
    date: "2025-10-13",
    time: "10:00",
    category: "upcoming",
  },
  {
    name: "Sophia",
    car: "Mustang",
    date: "2025-10-12",
    time: "09:30",
    category: "completed",
  },
  {
    name: "Ethan",
    car: "Civic",
    date: "2025-10-11",
    time: "13:00",
    category: "upcoming",
  },
  {
    name: "Olivia",
    car: "Corolla",
    date: "2025-10-10",
    time: "15:45",
    category: "cancelled",
  },
  {
    name: "Aiden",
    car: "Accord",
    date: "2025-10-09",
    time: "08:15",
    category: "completed",
  },
  {
    name: "Isabella",
    car: "Camry",
    date: "2025-10-08",
    time: "12:30",
    category: "upcoming",
  },
  {
    name: "Mason",
    car: "Mustang",
    date: "2025-10-07",
    time: "11:00",
    category: "cancelled",
  },
  {
    name: "Emma",
    car: "Civic",
    date: "2025-10-06",
    time: "14:15",
    category: "upcoming",
  },
  {
    name: "Logan",
    car: "Corolla",
    date: "2025-10-05",
    time: "09:45",
    category: "completed",
  },
  {
    name: "Ava",
    car: "Accord",
    date: "2025-10-04",
    time: "16:00",
    category: "upcoming",
  },
  {
    name: "Lucas",
    car: "Camry",
    date: "2025-10-03",
    time: "10:30",
    category: "completed",
  },
  {
    name: "Mia",
    car: "Mustang",
    date: "2025-10-02",
    time: "13:45",
    category: "cancelled",
  },
  {
    name: "James",
    car: "Civic",
    date: "2025-10-01",
    time: "15:00",
    category: "upcoming",
  },
  {
    name: "Charlotte",
    car: "Corolla",
    date: "2025-09-30",
    time: "11:15",
    category: "completed",
  },
  {
    name: "Benjamin",
    car: "Accord",
    date: "2025-09-29",
    time: "09:00",
    category: "upcoming",
  },
  {
    name: "Amelia",
    car: "Camry",
    date: "2025-09-28",
    time: "14:30",
    category: "completed",
  },
  {
    name: "Henry",
    car: "Mustang",
    date: "2025-09-27",
    time: "10:45",
    category: "cancelled",
  },
  {
    name: "Ella",
    car: "Civic",
    date: "2025-09-26",
    time: "12:00",
    category: "upcoming",
  },
  {
    name: "Jackson",
    car: "Corolla",
    date: "2025-09-25",
    time: "08:30",
    category: "completed",
  },
  {
    name: "Harper",
    car: "Accord",
    date: "2025-09-24",
    time: "16:15",
    category: "upcoming",
  },
  {
    name: "Sebastian",
    car: "Camry",
    date: "2025-09-23",
    time: "11:30",
    category: "cancelled",
  },
  {
    name: "Scarlett",
    car: "Mustang",
    date: "2025-09-22",
    time: "13:15",
    category: "completed",
  },
  {
    name: "Alexander",
    car: "Civic",
    date: "2025-09-21",
    time: "15:45",
    category: "upcoming",
  },
  {
    name: "Victoria",
    car: "Corolla",
    date: "2025-09-20",
    time: "09:30",
    category: "completed",
  },
  {
    name: "Daniel",
    car: "Accord",
    date: "2025-09-19",
    time: "10:15",
    category: "upcoming",
  },
  {
    name: "Lily",
    car: "Camry",
    date: "2025-09-18",
    time: "14:00",
    category: "cancelled",
  },
  {
    name: "Matthew",
    car: "Mustang",
    date: "2025-09-17",
    time: "12:45",
    category: "upcoming",
  },
  {
    name: "Grace",
    car: "Civic",
    date: "2025-09-16",
    time: "16:30",
    category: "completed",
  },
  {
    name: "David",
    car: "Corolla",
    date: "2025-09-15",
    time: "09:00",
    category: "upcoming",
  },
  {
    name: "Hannah",
    car: "Accord",
    date: "2025-09-14",
    time: "11:30",
    category: "completed",
  },
  {
    name: "Joseph",
    car: "Camry",
    date: "2025-09-13",
    time: "13:00",
    category: "upcoming",
  },
  {
    name: "Zoe",
    car: "Mustang",
    date: "2025-09-12",
    time: "15:15",
    category: "cancelled",
  },
  {
    name: "Samuel",
    car: "Civic",
    date: "2025-09-11",
    time: "08:45",
    category: "upcoming",
  },
  {
    name: "Chloe",
    car: "Corolla",
    date: "2025-09-10",
    time: "10:00",
    category: "completed",
  },
  {
    name: "Ryan",
    car: "Accord",
    date: "2025-09-09",
    time: "12:30",
    category: "upcoming",
  },
  {
    name: "Sofia",
    car: "Camry",
    date: "2025-09-08",
    time: "14:45",
    category: "completed",
  },
  {
    name: "Nathan",
    car: "Mustang",
    date: "2025-09-07",
    time: "09:15",
    category: "cancelled",
  },
  {
    name: "Maya",
    car: "Civic",
    date: "2025-09-06",
    time: "11:00",
    category: "upcoming",
  },
  {
    name: "Owen",
    car: "Corolla",
    date: "2025-09-05",
    time: "13:30",
    category: "completed",
  },
];
